version: 0.0
os: linux
files:
  - source: target/devsecops-app-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/app/
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
