name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven (package)
        run: mvn -B -DskipTests clean package

      - name: Run OWASP Dependency Check (report-only)
        run: mvn org.owasp:dependency-check-maven:check -DskipTests || true

      - name: Run tfsec (IaC) if terraform exists
        run: |
          if [ -d "terraform" ]; then
            docker run --rm -v "$(pwd)":/src aquasec/tfsec /src || true
          else
            echo "No terraform folder; skipping tfsec"
          fi

      - name: Run PII detector (report-only)
        run: python3 tools/pii_detector.py || true

      - name: Generate summary (report)
        run: python3 tools/generate_summary.py || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.json
            reports/**

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "target/*.jar"
          target: "/home/ec2-user/app/"

      - name: Restart App on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'devsecops-app' || true
            nohup java -jar /home/ec2-user/app/*.jar > /home/ec2-user/app/app.log 2>&1 &
            sleep 2
            curl -sS http://localhost:8080/health || (cat /home/ec2-user/app/app.log && exit 1)
